#!/bin/bash
mkdir ~/research
echo "A Quick System Audit Script" > ~/research/sys_info.txt
date > ~/research/sys_info.txt
find / -type f -perm 777 2>/dev/null > ~/research/sys_info.txt
echo -e "\nTop 10 Processes" > ~/research/sys_info.txt
ps aux -m | head -11 | awk {'print $1, $2, $3, $4, $11'} > ~/research/sys_info.txt
echo "Mashine Type Info:" > ~/research/sys_info.txt
echo $MACHTYPE > ~/research/sys_info.txt
echo -e "Uname info: $(uname -a) \n" > ~/research/sys_info.txt
echo "IP Info: $(ip addr | head -9 | tail -2) " > ~/research/sys_info.txt
echo "Hostname: $(hostname -s) " > ~/research/sys_info.txt
echo "DNS Servers: " > ~/research/sys_info.txt
cat /etc/resolv.conf > ~/research/sys_info.txt
echo "Memory Info:" > ~/research/sys_info.txt
free > ~/research/sys_info.txt
echo -e "\nCPU Info:" > ~/research/sys_info.txt
lscpu | grep CPU > ~/research/sys_info.txt
echo -e "\nDisk Usage:" > ~/research/sys_info.txt
df -H | head -2 > ~/research/sys_info.txt
echo -e "\nWho is logged in: \n $(who -a) \n" > ~/research/sys_info.txt 
